"""empty message

Revision ID: 0f527ef0e023
Revises: 91bd132703ca
Create Date: 2017-02-20 06:05:59.122356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f527ef0e023'
down_revision = '91bd132703ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_avatar_hash', sa.String(length=32), nullable=True))
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('users', '_avatar_hash')
    # ### end Alembic commands ###
