"""empty message

Revision ID: 8b61642b1198
Revises: 0f527ef0e023
Create Date: 2017-02-20 06:10:13.037822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b61642b1198'
down_revision = '0f527ef0e023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.drop_column('users', '_avatar_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_avatar_hash', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
